// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwdwfbpdzwgtlvbevzyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3ZHdmYnBkendndGx2YmV2enlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODM2NjgsImV4cCI6MjA3MDI1OTY2OH0.CAm4Mlck150HxCvTji0KroLWHWwyuuvsGrdizn_RRkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});